packages:
  - .
  - doc

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  vite@<=5.4.19: '>=5.4.20'
  vite@>=5.2.6 <=5.4.20: '>=5.4.21'
  vite@>=6.0.0 <=6.3.5: '>=6.3.6'
  vite@>=6.0.0 <=6.4.0: '>=6.4.1'
